### ISSUE TITLE
vercel 배포 과정 에러: default props가 프리렌더시 undefined로 뜨는 현상

### ISSUE THREAD

**Issue by blueprint-12** [blueprint-12/react-testing-project#1]
>vercel 배포 시, prerender 과정에서 props의 값이 undefined 로 뜨는 문제

## 개념 설명
getStaticProps 훅을 사용하면, 넥스트의 prerender를 하기 전에 의존성이 있는 데이터를 먼저 fetching해 올 수 있다. 
(useEffect의 첫 렌더링 시에 데이터를 패칭해 오는 것과 비슷해 보이지만 next의 훅은 렌더링 이전에 데이터 패칭을 해오는 거 같다.)
## 문제상황
로컬 환경에서 build를 했을 때에는 문제가 없었는데 vercel을 통해 배포하니 getStaticProps의 props가 prerender 시, undefined로 떠서 배포에서 계속 error가 뜬다. (배포 실패)
## 해결 방법 
1. 데이터를 fetching하는 비동기 함수를 분리하여 default props의 인자로 넘겨줄 때, await 패칭함수() // 호출을 통해서 해결할 수 있을 거 같다. 즉, 외부데이터로 http요청 함수를 분리하고 해당 함수를 불러와서 getStaticProps에 가져와 사용 `단점으로 함수를 한 번 더 호출하기 때문에 성능 저하를 불러올 수 있다.`
3. 외에도  해당 페이지의 프롭스로 { data }  객체 구조분해할당 문법으로 내려주는 방식을 그냥 props 객체 자체로 내려주면 해결된다는 방법이 있었다. (실패 -ref: [d433fa9](https://github.com/blueprint-12/react-testing-project/commit/d433fa9de5dcb6ef85b006ccb4b78eecf8ad1610))
4. 가장 간단하게 return 문에서 데이터가 undefined(즉, 비동기 처리가 완료되지 않는 시점이라면) fallback 컴포넌트를 보여준다. => `하지만 getStaticProps가 서버 사이드에서 실행된다는 점을 고려하면 undefined처리는 가능할 지 몰라도 prerender시 contents를 읽을 수 없어, SEO는 되지 않을 것으로 생각한다. `

###  문제 상황 재분석 [2023 04 12 updated] 
getStaticProps의 사용법에 대해서 next docs를 훑어봐도 아무래도 잘못 처리한 부분이 없다는 생각이 들었다. fetch하는 함수 내용을 천천히 보니 주소로만 호출을 하는게 아니라 `로컬 변수가 필요한 api`라는 것을 확인했다. (당연하다. 내 notion의 데이터를 가져오는 api이므로) 이 부분을 간과했고 내가 배포할 시 사용하는 Vercel이 깃허브의 repo에 의존해서 배포하고 있다는 것을 인지하게 됐다. `즉, env.local 에 담겨있는 프라이빗데이터에 접근을 아예 하지 못한다는 소리 `
=> 내가 사용하는 PaaS(Platfrom as a Service)인 Vercel에 변수를 알려주는 것만 하면 해결될 거 같다!

**Comment by blueprint-12** [comment]
## 해결 방법 2: 블로그 참조 해결방안 props 객체 자체 전달 솔루션 
<img width="688" alt="배포이슈" src="https://user-images.githubusercontent.com/86911858/231353186-3385abd1-2a14-45c5-9b19-ff152f1147e6.png">
<hr/>

> 배포는 `실패` 했으며 아래는 이전과 동일한 `에러메세지` 를 출력하고 있다. 

```
TypeError: Cannot read properties of undefined (reading 'length')
13:49:24.391 | at Projects (/vercel/path0/my-next-blog/.next/server/pages/projects.js:194:62)
13:49:24.394 | at Wc (/vercel/path0/my-next-blog/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
13:49:24.394 | at Zc (/vercel/path0/my-next-blog/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
13:49:24.395 | at Z (/vercel/path0/my-next-blog/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
13:49:24.395 | at $c (/vercel/path0/my-next-blog/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
13:49:24.395 | at bd (/vercel/path0/my-next-blog/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
13:49:24.395 | at Z (/vercel/path0/my-next-blog/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
13:49:24.395 | at Zc (/vercel/path0/my-next-blog/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
13:49:24.396 | at Z (/vercel/path0/my-next-blog/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
13:49:24.396 | at Zc (/vercel/path0/my-next-blog/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
```

**Comment by blueprint-12** [comment]
## 해결 방법
우선 원인은 환경 변수 문제가 맞았다. 또한, 나는 dotenv를 사용하고 있기 때문에 dotenv의 환경변수를 브라우저에 배포했을 때에도 연결해주는 부분이 필요했다. 
1. .env.local 파일을 로컬 환경이 아닌 곳에서도 적용할 수 있도록 .env 로 변경 
2. config 파일을 따로 만들어 dotenv의 환경변수를 프로젝트에 연결 
3. vercel 에 환경변수를 추가해주는 작업(env파일은 깃허브 repo에 올라가지 않으므로) -> 재배포

**Comment by blueprint-12** [comment]
참고로 로컬에서 빌드를 했을 때에는 문제가 없었기 때문에 vercel 의 CICD에서 문제가 발생하는 줄 알았다. 

[로컬 빌드 시, 모습]
<img width="611" alt="next 프로젝트 로컬 빌드" src="https://user-images.githubusercontent.com/86911858/231500136-750e820c-2d05-4b29-8b67-32e2cfcf44f7.png">

빌드 시, 첫번째 로드가 빨간 표시로 된 static 페이지 2개는 로티 애니메이션을 담고있는 페이지이다. 
로티 파일이 커서 일종의 큰 데이터를 최적화하라는 경고 표시인 줄 알았으나 찾아보니 
`단순히 첫 로드시 170kb를 넘어가는 파일을 나타내는 표시였다. 고로 사이즈가 너무 크다고 볼 수는 없다.`

혹시 몰라 로티 애니메이션을 최적화하는 방법을 공부해봤다 첫번째로 chatGPT를 활용해 보았다. 
=> chatGPT가 알려준 방식대로 해보니 전혀 효과도 없을 뿐더러 추가적으로 설치한 플러그인의 사이즈가 어마무시했다. 

궁금해서 로티 애니메이션을 next에서 최적화하는 방법에 다룬 stackoverflow글을 발견했다. 
[스택 오버플로우 로티 애니메이션 최적화](https://stackoverflow.com/questions/69282996/lottie-files-reducing-performance-on-nextjs-app)  

여담: `네트워크 탭에서 3G slow로 환경을 설정하고 확인하니 static 페이지라 그런지 그렇게 느린 느낌은 받지 못했다. 의외로 굉장히 빠르다..?`
